# Generated by Django 5.2.4 on 2025-08-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='citizen_email',
            new_name='contact',
        ),
    ]
